version: "3.9"

services:
  backend:
    build: .
    ports:
      - "1000:1000"
    environment:
      - APP_ENV=production
      - APP_PORT=1000
      - DATABASE_URL=postgresql://kalvium:kalvium123@db:5432/kalviumdb
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: kalvium
      POSTGRES_PASSWORD: kalvium123
      POSTGRES_DB: kalviumdb
    ports:
      - "5432:5432"