name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install fastapi pytest httpx pytest-html
    - name: Run tests
      run: |
        pytest --html=report.html test_main.py
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: backend-test-report
        path: report.html
        pytest test_main.py

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit security scan
      run: bandit -r . -f html -o bandit-report.html || true
    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-security-report
        path: bandit-report.html
