name: Docker Image Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build -t my-app:latest ./backend
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.13.0
        with:
          image-ref: 'my-app:latest'
          format: 'table'
          output: 'trivy-report.txt'
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
